## **LAB - Testes e Análises dos Dados de Medidores**

#### Esse notebook visa realizar testes e análises para o desenvolvimento do problema envolvendo as imagens dos medidores tirados pelos leituristas da Neroenergia.

- Configurações iniciais

In [2]:
# Bibliotecas
import pandas as pd
import numpy as np
import cv2
import matplotlib.pyplot as plt
import glob

# Pandas configs
pd.set_option("display.max_columns", None)
pd.set_option('display.max_colwidth', None)

- **Tópico 1 -** Análise dos arquivos `CSVs`

In [15]:
# Analisando estrutura dos dados CSVs
sheets = glob.glob('../data/sheets/*.csv')
df = pd.concat([pd.read_csv(sheet, sep=';') for sheet in sheets])

display(df.head())
df.info()

,Numero do medidor,Posicao do medidor lida,Nota de Leitura Atual,Foto do medidor
0,3213492267,6521,NaN,PSP_EXTRATLEITIMPL_030726_0121_20000000012852988478_000.jpg
1,40482962,9729,L131,PSP_EXTRATLEITIMPL_030726_0121_20000000003053017019_000.jpg
2,30501853,24788,NaN,PSP_EXTRATLEITIMPL_030726_0121_20000000006502995976_000.jpg
3,82861661,20512,NaN,PSP_EXTRATLEITIMPL_030726_0121_20000000012552976989_000.jpg
4,3221134515,1698,NaN,PSP_EXTRATLEITIMPL_030726_0121_20000000017102988986_000.jpg

<class 'pandas.core.frame.DataFrame'>
Index: 13669 entries, 0 to 3259
Data columns (total 4 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Numero do medidor        13669 non-null  object
 1   Posicao do medidor lida  13669 non-null  int64
 2   Nota de Leitura Atual    4560 non-null   object
 3   Foto do medidor          11474 non-null  object
dtypes: int64(1), object(3)
memory usage: 533.9+ KB

Após análise inicial dos dados, é possível ver que as colunas `Numero do medidor` e `Posicao do medidor lida` estão todas preenchidas. Já as demais colunas estão com uma boa quantidade de valores nulos. O próximo passo é identificar mais detalhadamente esses valores.

In [17]:
# Verificando colunas com valores nulos
print("Verificação de valores nulos [Nota de Leitura Atual]:", df["Nota de Leitura Atual"].isnull().sum())
print("Verificação de valores nulos [Foto do medidor]:", df["Foto do medidor"].isnull().sum())

Verificação de valores nulos [Nota de Leitura Atual]: 9109
Verificação de valores nulos [Foto do medidor]: 2195

In [26]:
# Identificando os valores nulos com mais detalhe
print("Nota de Leitura Atual - Valores nulos:")
display(df[df["Nota de Leitura Atual"].isnull()].head(15))

print("Foto do medidor - Valores nulos:")
df[df["Foto do medidor"].isnull()].head(15)

Nota de Leitura Atual - Valores nulos:

,Numero do medidor,Posicao do medidor lida,Nota de Leitura Atual,Foto do medidor
0,3213492267,6521,NaN,PSP_EXTRATLEITIMPL_030726_0121_20000000012852988478_000.jpg
2,30501853,24788,NaN,PSP_EXTRATLEITIMPL_030726_0121_20000000006502995976_000.jpg
3,82861661,20512,NaN,PSP_EXTRATLEITIMPL_030726_0121_20000000012552976989_000.jpg
4,3221134515,1698,NaN,PSP_EXTRATLEITIMPL_030726_0121_20000000017102988986_000.jpg
5,82806814,14247,NaN,PSP_EXTRATLEITIMPL_030726_0121_20000000018003004648_000.jpg
8,3220820563,606,NaN,PSP_EXTRATLEITIMPL_030726_0121_20000000000202980515_000.jpg
9,3172755150,23591,NaN,NaN
10,L23637,29997,NaN,PSP_EXTRATLEITIMPL_030726_0121_20000000006602993796_000.jpg
12,3201867893,32174,NaN,PSP_EXTRATLEITIMPL_030726_0121_20000000015502982528_000.jpg
15,50628191,85044,NaN,PSP_EXTRATLEITIMPL_030726_0121_20000000012053008152_000.jpg
16,80594658,4330,NaN,PSP_EXTRATLEITIMPL_030726_0121_20000000013052996127_000.jpg
18,90554247,8004,NaN,PSP_EXTRATLEITIMPL_030726_0121_20000000005653000347_000.jpg
19,IC60087,38521,NaN,NaN
20,30497350,17226,NaN,NaN
21,3171772655,94296,NaN,PSP_EXTRATLEITIMPL_030726_0121_20000000001252992676_000.jpg

Foto do medidor - Valores nulos:

,Numero do medidor,Posicao do medidor lida,Nota de Leitura Atual,Foto do medidor
9,3172755150,23591,NaN,NaN
19,IC60087,38521,NaN,NaN
20,30497350,17226,NaN,NaN
31,3214285281,117062,NaN,NaN
32,3181710895,383632,NaN,NaN
43,6252249727/3191280490,821,NaN,NaN
44,3241205397,19732,NaN,NaN
54,3161420840,233093,NaN,NaN
58,3180658687,777398,NaN,NaN
66,3181692820,298285,NaN,NaN
86,3161420270,380195,NaN,NaN
87,3232883862,94556,NaN,NaN
106,3181691688,166321,NaN,NaN
108,3230077206,120313,NaN,NaN
189,3191230379,9278,NaN,NaN